name: Build, Test Separate Job

on:
  push

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  SOME_MESSAGE: 'Some Random Message!'
  BUILD_SHA: ${{ github.sha }}

jobs:
  context-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Log Context
        run: |
          echo ">>>>>>>>>>>>>>>>>>>"
          echo "SHA: $BUILD_SHA"
          echo ">>>>>>>>>>>>>>>>>>>"

  build:
    needs: context-log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Compile & Build Project
        run: mvn clean package -DskipTests

      - name: Closing statement
        run: |
          echo ">>>>>>>>>>>>>>>>>"
          echo "Build Completed!"
          echo "Secret is: ${{ secrets.MY_SEC }}"
          echo ">>>>>>>>>>>>>>>>>"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Run Tests
        run: mvn clean test

      - name: Closing statement
        run: |
          echo "Test Job completed"
          echo "Message: $SOME_MESSAGE"
